name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set baseline images
        run: java -jar ImageTester_3.1.3.jar -fb "Example: Image Tester CLI" -f files/
        
      - name: Test modified images
        run: java -jar ImageTester_3.1.3.jar -fb "Example: Image Tester CLI" -f files_modified/
